import { isPlaceholderTeam } from "~/lib/fifa-sync";

const COUNTRY_CODES: Record<string, string> = {
  afghanistan: "AF",
  albania: "AL",
  algeria: "DZ",
  angola: "AO",
  argentina: "AR",
  armenia: "AM",
  australia: "AU",
  austria: "AT",
  azerbaijan: "AZ",
  bahrain: "BH",
  belgium: "BE",
  bolivia: "BO",
  "bosnia and herzegovina": "BA",
  brazil: "BR",
  bulgaria: "BG",
  cameroon: "CM",
  canada: "CA",
  "cabo verde": "CV",
  "congo dr": "CD",
  chile: "CL",
  china: "CN",
  colombia: "CO",
  "costa rica": "CR",
  croatia: "HR",
  cuba: "CU",
  curacao: "CW",
  curaçao: "CW",
  cyprus: "CY",
  "czech republic": "CZ",
  czechia: "CZ",
  denmark: "DK",
  ecuador: "EC",
  egypt: "EG",
  england: "GB",
  estonia: "EE",
  finland: "FI",
  france: "FR",
  georgia: "GE",
  germany: "DE",
  ghana: "GH",
  greece: "GR",
  haiti: "HT",
  honduras: "HN",
  hungary: "HU",
  iceland: "IS",
  india: "IN",
  indonesia: "ID",
  iran: "IR",
  "ir iran": "IR",
  iraq: "IQ",
  ireland: "IE",
  israel: "IL",
  italy: "IT",
  "ivory coast": "CI",
  "cote d'ivoire": "CI",
  "côte d'ivoire": "CI",
  jamaica: "JM",
  japan: "JP",
  jordan: "JO",
  kazakhstan: "KZ",
  kenya: "KE",
  "korea republic": "KR",
  "south korea": "KR",
  kosovo: "XK",
  kuwait: "KW",
  latvia: "LV",
  lithuania: "LT",
  luxembourg: "LU",
  malaysia: "MY",
  mali: "ML",
  malta: "MT",
  mexico: "MX",
  morocco: "MA",
  netherlands: "NL",
  "new zealand": "NZ",
  nigeria: "NG",
  "north macedonia": "MK",
  "northern ireland": "GB",
  norway: "NO",
  oman: "OM",
  pakistan: "PK",
  panama: "PA",
  paraguay: "PY",
  peru: "PE",
  philippines: "PH",
  poland: "PL",
  portugal: "PT",
  qatar: "QA",
  romania: "RO",
  russia: "RU",
  "russian federation": "RU",
  "saudi arabia": "SA",
  scotland: "GB",
  senegal: "SN",
  serbia: "RS",
  slovakia: "SK",
  slovenia: "SI",
  "south africa": "ZA",
  spain: "ES",
  sweden: "SE",
  switzerland: "CH",
  syria: "SY",
  thailand: "TH",
  tunisia: "TN",
  turkey: "TR",
  turkiye: "TR",
  türkiye: "TR",
  ukraine: "UA",
  "united arab emirates": "AE",
  "united states": "US",
  usa: "US",
  uruguay: "UY",
  uzbekistan: "UZ",
  venezuela: "VE",
  vietnam: "VN",
  wales: "GB",
  zambia: "ZM",
};

function isoToFlagEmoji(code: string): string | null {
  const upper = code.toUpperCase();
  if (!/^[A-Z]{2}$/.test(upper)) return null;

  return String.fromCodePoint(
    ...upper.split("").map((char) => 0x1f1e6 + char.charCodeAt(0) - 65),
  );
}

export function getCountryIsoCode(countryName: string): string | null {
  if (isPlaceholderTeam(countryName)) return null;

  const key = countryName.trim().toLowerCase();
  return COUNTRY_CODES[key] ?? null;
}

export function getCountryFlagEmoji(countryName: string): string {
  const code = getCountryIsoCode(countryName);
  if (!code) return "🏳️";

  return isoToFlagEmoji(code) ?? "🏳️";
}
